### ISSUE TITLE
Revamp HowTo - Import Export data

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph-docs#352]
Create a HowTo entry for "importing and exporting your data"
Merge info from 
https://dgraph.io/docs/cloud/admin/import-export/
https://dgraph.io/docs/deploy/fast-data-loading/overview/
https://dgraph.io/docs/deploy/fast-data-loading/live-loader/
https://dgraph.io/docs/deploy/fast-data-loading/bulk-loader/
and there is a reference to export import in https://dgraph.io/docs/cloud/cloud-api/backup/

Clean old pages and reference this howto when we mention export import.

**Comment by Rajakavitha1** [comment]
Hi @rderbier I found additional pages for export in https://dgraph.io/docs/deploy/dgraph-administration/#exporting-database. This is for exporting data from a self hosted instance.

**Comment by damonfeldman** [comment]
We also need to update export/import to say that you need to strip all the dgraph.xxx predicates from an RDF export in order to import it (other than dgraph.type). The process is more complex if ACLs are in use. I believe this is because an export exports all data including certain config or schema elements, but an import expects the data portion to be separate from the schema and any configs.

**Comment by Rajakavitha1** [comment]
@damonfeldman  During the technical review please all the caveats that need to be covered in the documentation.
